# Generated by Django 5.2.17 on 2026-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('news_type', models.CharField(choices=[('主线剧情', '主线剧情'), ('限时活动', '限时活动'), ('召唤公告', '召唤公告')], max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
