# Generated by Django 2.2.4 on 2026-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20260508_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2026-05-18', max_length=20, verbose_name='出生日期'),
        ),
    ]
