# Generated by Django 2.2.4 on 2026-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='description',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='mynew',
            name='title',
            field=models.CharField(max_length=50, verbose_name='新闻标题'),
        ),
    ]
